'use client'

import { useState } from 'react'

interface Props {
  userId: string
}

const tones = [
  { label: 'Default', value: 'default' },
  { label: 'Short', value: 'short' },
  { label: 'Direct', value: 'direct' },
  { label: 'Technical', value: 'technical' },
  { label: 'Friendly', value: 'friendly' },
]

export default function GenerateFollowUpButton({ userId }: Props) {
  const [loading, setLoading] = useState(false)
  const [sending, setSending] = useState(false)
  const [subject, setSubject] = useState('')
  const [body, setBody] = useState('')
  const [tone, setTone] = useState('default')
  const [error, setError] = useState('')
  const [copySuccess, setCopySuccess] = useState('')
  const [sendSuccess, setSendSuccess] = useState('')

  async function handleGenerate() {
    try {
      setLoading(true)
      setError('')
      setCopySuccess('')
      setSendSuccess('')

      const res = await fetch(`/api/leads/${userId}/follow-up`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ tone }),
      })

      const data = await res.json()

      if (!res.ok) {
        throw new Error(data.error || 'Generation failed')
      }

      setSubject(data.email.subject || '')
      setBody(data.email.body || '')
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Generation failed')
    } finally {
      setLoading(false)
    }
  }

  async function handleCopy() {
    try {
      const combined = `Subject: ${subject}\n\n${body}`
      await navigator.clipboard.writeText(combined)
      setCopySuccess('Copied to clipboard')
      setTimeout(() => setCopySuccess(''), 2000)
    } catch {
      setError('Failed to copy email')
    }
  }

  async function handleSend() {
    try {
      setSending(true)
      setError('')
      setCopySuccess('')
      setSendSuccess('')

      const res = await fetch(`/api/leads/${userId}/send-follow-up`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          subject,
          message: body,
          autoGenerated: false,
        }),
      })

      const data = await res.json()

      if (!res.ok) {
        throw new Error(data.error || 'Send failed')
      }

      setSendSuccess(`Email sent to ${data.recipientEmail}`)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Send failed')
    } finally {
      setSending(false)
    }
  }

  return (
    <div className="bg-white rounded-xl shadow p-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-gray-900">Follow-Up Generator</h2>
          <p className="text-sm text-gray-600 mt-1">
            Generate, edit, copy, and send a context-aware outreach email.
          </p>
        </div>

        <button
          onClick={handleGenerate}
          disabled={loading}
          className="inline-flex items-center justify-center px-4 py-2 rounded-lg bg-tre1-teal text-white font-semibold hover:bg-teal-600 disabled:opacity-50 transition"
        >
          {loading ? 'Generating...' : 'Generate Follow-Up Email'}
        </button>
      </div>

      <div className="flex flex-wrap gap-2 mt-4">
        {tones.map((t) => (
          <button
            key={t.value}
            onClick={() => setTone(t.value)}
            className={`px-3 py-1 rounded-full text-xs font-medium transition ${
              tone === t.value
                ? 'bg-tre1-teal text-white'
                : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
            }`}
          >
            {t.label}
          </button>
        ))}
      </div>

      {error && (
        <div className="mt-4 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">
          {error}
        </div>
      )}

      {copySuccess && (
        <div className="mt-4 rounded-lg border border-green-200 bg-green-50 p-4 text-sm text-green-700">
          {copySuccess}
        </div>
      )}

      {sendSuccess && (
        <div className="mt-4 rounded-lg border border-green-200 bg-green-50 p-4 text-sm text-green-700">
          {sendSuccess}
        </div>
      )}

      {(subject || body) && (
        <div className="mt-6 space-y-4">
          <div>
            <label
              htmlFor="followup-subject"
              className="block text-sm text-gray-500 mb-1"
            >
              Subject
            </label>
            <input
              id="followup-subject"
              type="text"
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              className="w-full rounded-lg border border-gray-300 bg-white p-3 text-gray-900 focus:border-tre1-teal focus:outline-none focus:ring-2 focus:ring-tre1-teal/20"
              placeholder="Enter subject"
            />
          </div>

          <div>
            <label
              htmlFor="followup-body"
              className="block text-sm text-gray-500 mb-1"
            >
              Body
            </label>
            <textarea
              id="followup-body"
              value={body}
              onChange={(e) => setBody(e.target.value)}
              rows={10}
              className="w-full rounded-lg border border-gray-300 bg-white p-3 text-gray-800 whitespace-pre-wrap focus:border-tre1-teal focus:outline-none focus:ring-2 focus:ring-tre1-teal/20"
              placeholder="Enter follow-up body"
            />
          </div>

          <div className="flex flex-col sm:flex-row gap-3">
            <button
              onClick={handleCopy}
              disabled={!subject && !body}
              className="inline-flex items-center justify-center px-4 py-2 rounded-lg border border-gray-300 text-gray-800 font-semibold hover:bg-gray-50 disabled:opacity-50 transition"
            >
              Copy Draft
            </button>

            <button
              onClick={handleSend}
              disabled={sending || !subject.trim() || !body.trim()}
              className="inline-flex items-center justify-center px-4 py-2 rounded-lg bg-tre1-orange text-white font-semibold hover:bg-orange-600 disabled:opacity-50 transition"
            >
              {sending ? 'Sending...' : 'Send via Resend'}
            </button>
          </div>
        </div>
      )}
    </div>
  )
}