import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { sendLeadFollowUpEmail } from '@/lib/resend'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const FOLLOW_UP_COOLDOWN_DAYS = 7

export async function POST(
  request: NextRequest,
  { params }: { params: { userId: string } }
) {
  try {
    const body = await request.json()
    const { subject, message, autoGenerated = false } = body

    if (!subject || !message) {
      return NextResponse.json(
        { error: 'Missing subject or message' },
        { status: 400 }
      )
    }

    const { data: profile, error: profileError } = await supabase
      .from('profiles')
      .select('contact_email, display_name, first_name, last_name')
      .eq('id', params.userId)
      .single()

    if (profileError || !profile) {
      return NextResponse.json(
        { error: 'Lead profile not found' },
        { status: 404 }
      )
    }

    const recipientEmail = profile.contact_email

    if (!recipientEmail) {
      return NextResponse.json(
        { error: 'No verified contact email available for this lead' },
        { status: 400 }
      )
    }

    const cooldownStart = new Date(
      Date.now() - FOLLOW_UP_COOLDOWN_DAYS * 24 * 60 * 60 * 1000
    ).toISOString()

    const { data: recentOutreach, error: recentOutreachError } = await supabase
      .from('lead_outreach')
      .select('id, created_at, subject')
      .eq('user_id', params.userId)
      .eq('channel', 'email')
      .gte('created_at', cooldownStart)
      .order('created_at', { ascending: false })
      .limit(1)

    if (recentOutreachError) {
      console.warn('Lead outreach cooldown lookup warning:', recentOutreachError)
    }

    if (recentOutreach && recentOutreach.length > 0) {
      return NextResponse.json(
        {
          error: `A follow-up email was already sent within the last ${FOLLOW_UP_COOLDOWN_DAYS} days`,
          lastSentAt: recentOutreach[0].created_at,
          lastSubject: recentOutreach[0].subject,
        },
        { status: 400 }
      )
    }

    const displayName =
      profile.display_name ||
      [profile.first_name, profile.last_name].filter(Boolean).join(' ') ||
      recipientEmail

    const result = await sendLeadFollowUpEmail(
      recipientEmail,
      displayName,
      subject,
      message
    )

    if (!result.success) {
      return NextResponse.json(
        { error: 'Failed to send follow-up email' },
        { status: 500 }
      )
    }

    const { error: outreachError } = await supabase
      .from('lead_outreach')
      .insert({
        user_id: params.userId,
        recipient_email: recipientEmail,
        subject,
        body: message,
        channel: 'email',
        status: 'sent',
        auto_generated: autoGenerated,
      })

    if (outreachError) {
      console.warn('Lead outreach logging warning:', outreachError)
    }

    return NextResponse.json({
      success: true,
      message: 'Follow-up email sent successfully',
      recipientEmail,
    })
  } catch (error) {
    console.error('Send follow-up route error:', error)
    return NextResponse.json(
      { error: 'Failed to send follow-up email' },
      { status: 500 }
    )
  }
}